using DevExpress.XtraGrid.Views.Base;
using DevExpress.XtraGrid.Views.Grid;
using MetroFramework.Forms;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace QuanLiTinBao
{
    public partial class FormQuanLi : MetroForm
    {
        /*TODO1: nhung  tin bao da xu li roi thi nghiep vu bi disable*/
       // panelMain panel_main = null;
        Boolean isClosed=true;
        FormXuLiKhac formxulikhac;
        public FormQuanLi()
        {
            InitializeComponent();
            // panel_main = new panelMain(this);
            // panel_main.swipe();
           
            navframe_content_managment.SelectedPage = navigationPage1;
            formxulikhac= new FormXuLiKhac();
            formxulikhac.TaoForm += button_taoform_Click;
            
            //   pnlMenuTinBao.Save += barButtonItem_save_ItemClick();

            // This line of code is generated by Data Source Configuration Wizard
            chuyenCoQuanTableAdapter1.Fill(qltbDataSet21.ChuyenCoQuan);
            // This line of code is generated by Data Source Configuration Wizard
            xuLyKhacTableAdapter1.Fill(qltbDataSet22.XuLyKhac);
        }

        private void button_taoform_Click(object sender, EventArgs e)
        {
            //gridview cua xu li khac
            gridView3.AddNewRow();

            //int rowHandle = gridView3.GetRowHandle(gridView3.DataRowCount);
            //if (gridView3.IsNewItemRow(rowHandle))
            //{
            //    gridView3.SetRowCellValue(rowHandle, gridView3.Columns[0], formxulikhac.SoQuyetDinh);
            //    gridView3.SetRowCellValue(rowHandle, gridView3.Columns[1], formxulikhac.CanBo);
            //    gridView3.SetRowCellValue(rowHandle, gridView3.Columns[2], formxulikhac.NgayXL);
            //    gridView3.SetRowCellValue(rowHandle, gridView3.Columns[3], formxulikhac.SoTinBao);
            //    gridView3.SetRowCellValue(rowHandle, gridView3.Columns[4], formxulikhac.NoiDung);
            //}
        }

        private void barButtonItem_save_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

          
        }

        private void btn_menu_Click(object sender, EventArgs e)
        {
            if (isClosed == true)
            {
                //panel_menu.Visible = true;
                icon_managment.Visible = false;
                isClosed = false;
            }
            else
            {
               //panel_menu.Visible = false;
                icon_managment.Visible = true;
                isClosed = true;
                
            }
        }

        private void icon_trangchu_Click(object sender, EventArgs e)
        {

        }

        private void icon_tinbao_Click(object sender, EventArgs e)
        {
            navframe_content_managment.SelectedPage = page_tinbao ;
            nghiệpVụToolStripMenuItem1.Enabled = true;
            //menubar_tinbao.Visible = true;
        }

        private void icon_kt_Click(object sender, EventArgs e)
        {

        }

        private void icon_kkt_Click(object sender, EventArgs e)
        {

        }

        private void icon_hc_Click(object sender, EventArgs e)
        {

        }

        private void icon_ccq_Click(object sender, EventArgs e)
        {
            label_tentieude.Text = "Quản Lý Chuyển Cơ Quan";
            navframe_content_managment.SelectedPage = page_ccq;
            nghiệpVụToolStripMenuItem1.Enabled = false;
            
        }

        private void icon_khac_Click(object sender, EventArgs e)
        {
            label_tentieude.Text = "Quản Lý Xử Lí Khác";
            navframe_content_managment.SelectedPage = page_xlk;
            nghiệpVụToolStripMenuItem1.Enabled = false;
        }

        private void icon_dangxuat_Click(object sender, EventArgs e)
        {

        }

        private void btn_xoa_Click(object sender, EventArgs e)
        {

        }

        private void btn_xuatexcel_Click(object sender, EventArgs e)
        {

        }

        private void btn_nghiepvu_Click(object sender, EventArgs e)
        {

        }

     
        private void FormQuanLi_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'qLTBDataSet2.TinBao' table. You can move, or remove it, as needed.
            this.tinBaoTableAdapter.Fill(this.qLTBDataSet2.TinBao);
            

        }

        private void lưuToolStripMenuItem_Click(object sender, EventArgs e)
        {
            ColumnView view = gridcontrol_tinbao.FocusedView as ColumnView;
            view.CloseEditor();
            if (view.UpdateCurrentRow())
            {
                try
                {
                    this.Validate();
                    this.tinBaoTableAdapter.Update(this.qLTBDataSet2.TinBao);
                    MessageBox.Show("Cập nhật thành công");
                }
                catch
                {
                    MessageBox.Show("Cập nhật không thành công");
                }
            }
        }

        private void gridView1_ShowingEditor(object sender, CancelEventArgs e)
        {
            //gridview la bang tin bao


           // if (gridView1.FocusedColumn.FieldName == "SoTinBao" )
             //   e.Cancel = true;
        }

        private void gridView1_InitNewRow(object sender, InitNewRowEventArgs e)
        {
            //phai sort tang dan truoc khi lay du lieu
            // colSoTinBao.OptionsColumn.AllowEdit = true;

            this.qLTBDataSet2.TinBao.DefaultView.Sort = "SoTinBao";
            var t = gridView1.GetRowCellValue(gridView1.GetRowHandle(gridView1.RowCount - 2), 
               colSoTinBao).ToString();
            string[] cautructinbao = t.Split('-');
            int nam = Convert.ToInt32(cautructinbao[1]);
            int sotb = Convert.ToInt32(cautructinbao[2]);
            if (nam == DateTime.Now.Year)
            {
                sotb++;
            }
            else
            {
                nam = DateTime.Now.Year;
                sotb = 1;
            }
            string tinbaomoi = "TB-" + nam+"-" + sotb;
          
            gridView1.SetRowCellValue(e.RowHandle, colSoTinBao, tinbaomoi);
            gridView1.SetRowCellValue(e.RowHandle, colTinhTrang, "Chưa xử lý");
            gridView1.SetRowCellValue(e.RowHandle, colNgayNhan, DateTime.Now);
        }

        private void thêmToolStripMenuItem_Click(object sender, EventArgs e)
        {
            gridView1.AddNewRow();
        }

        private void xóaToolStripMenuItem_Click(object sender, EventArgs e)
        {
            gridView1.DeleteRow(gridView1.FocusedRowHandle);
        }

        private void sửaToolStripMenuItem_Click(object sender, EventArgs e)
        {
            gridView1.ShowEditForm();
        }

        private void xuấtExcelToolStripMenuItem_Click(object sender, EventArgs e)
        {
            if (xuatExcelDialog.ShowDialog() == DialogResult.OK)
            {
                if(xuatExcelDialog.Filter== "Excel 2010|*.xlsx")
                 gridView1.ExportToXlsx(xuatExcelDialog.FileName);
                else gridView1.ExportToXls(xuatExcelDialog.FileName);
            }
        }

        private void xửLýKhácToolStripMenuItem_Click(object sender, EventArgs e)
        {
            string sotinbao = gridView1.GetFocusedRowCellValue(colSoTinBao).ToString();
            string soquyetdinh;
            if (qLTBDataSet2.XuLyKhac.Rows.Count != 0)
            {
                this.qLTBDataSet2.XuLyKhac.DefaultView.Sort = "SoQuyetDinh";
                DataRow lastRow = qLTBDataSet2.XuLyKhac.Rows[qLTBDataSet2.XuLyKhac.Rows.Count - 1];
                soquyetdinh = lastRow["SoQuyetDinh"].ToString();
                string[] cautrucsqd = soquyetdinh.Split('-');
                int sqd = Convert.ToInt32(cautrucsqd[1]) + 1;
                soquyetdinh = cautrucsqd[0].ToString() + "-" + sqd.ToString();
            }
            else {
                soquyetdinh="XLK-0001";
            }
            //FormXuLiKhac formxulikhac = new FormXuLiKhac(sotinbao, soquyetdinh);
            formxulikhac.SoTinBao = sotinbao;
            formxulikhac.SoQuyetDinh = soquyetdinh;
            formxulikhac.Show();
        }

        private void gridView3_InitNewRow(object sender, InitNewRowEventArgs e)
        {
           // int rowHandle = gridView3.GetRowHandle(gridView3.DataRowCount);
          //  if (gridView3.IsNewItemRow(rowHandle))
            {
                gridView3.SetRowCellValue(e.RowHandle, gridView3.Columns[0], formxulikhac.SoQuyetDinh);
                gridView3.SetRowCellValue(e.RowHandle, gridView3.Columns[1], formxulikhac.CanBo);
                gridView3.SetRowCellValue(e.RowHandle, gridView3.Columns[2], formxulikhac.NgayXL);
                gridView3.SetRowCellValue(e.RowHandle, gridView3.Columns[3], formxulikhac.SoTinBao);
                gridView3.SetRowCellValue(e.RowHandle, gridView3.Columns[4], formxulikhac.NoiDung);
            }
        }
    }
}
