
using DevExpress.Utils.OAuth.Provider;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Base;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraPrinting;
using DevExpress.XtraPrintingLinks;
using MetroFramework.Forms;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;


namespace QuanLiTinBao
{
    public partial class FormQuanLi : MetroForm
    {
       // panelMain panel_main = null;
        Boolean isClosed=true;
        PrintingSystem ps;
        private void FormQuanLi_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'qLTBDataSet2.TinBao' table. You can move, or remove it, as needed.
            this.tinBaoTableAdapter.Fill(this.qltbDataSet21.TinBao);

        }

        public FormQuanLi()
        {
            InitializeComponent();
            // panel_main = new panelMain(this);
            // panel_main.swipe();
           
            navframe_content_managment.SelectedPage = navigationPage1;

            //   pnlMenuTinBao.Save += barButtonItem_save_ItemClick();

            // This line of code is generated by Data Source Configuration Wizard
             chuyenCoQuanTableAdapter1.Fill(qltbDataSet21.ChuyenCoQuan);
           // chuyenCoQuanTableAdapter1.Fill(qltbDataSet2.ChuyenCoQuan);

            // This line of code is generated by Data So4urce Configuration Wizard
             xuLyKhacTableAdapter1.Fill(qltbDataSet22.XuLyKhac);
            ps = new PrintingSystem();
            ps.XlSheetCreated += PrintingSystem_XlSheetCreated;

        }

       

        private void btn_menu_Click(object sender, EventArgs e)
        {
            if (isClosed == true)
            {
                //panel_menu.Visible = true;
                icon_managment.Visible = false;
                isClosed = false;
            }
            else
            {
               //panel_menu.Visible = false;
                icon_managment.Visible = true;
                isClosed = true;
                
            }
        }

        private void icon_trangchu_Click(object sender, EventArgs e)
        {

        }

        private void icon_tinbao_Click(object sender, EventArgs e)
        {
            navframe_content_managment.SelectedPage = page_tinbao ;
            nghiệpVụToolStripMenuItem1.Enabled = true;
            nghiệpVụToolStripMenuItem1.Enabled = true;
            thêmToolStripMenuItem1.Enabled = true;
            sửaToolStripMenuItem1.Enabled = true;
            xóaToolStripMenuItem1.Enabled = true;
            thêmToolStripMenuItem.Enabled = true;
            sửaToolStripMenuItem.Enabled = true;
            xóaToolStripMenuItem.Enabled = true;
            gridControl_xlk.EmbeddedNavigator.Buttons.Remove.Enabled = true;
            gridControl_xlk.EmbeddedNavigator.Buttons.Append.Enabled = true;
            //menubar_tinbao.Visible = true;
        }

        private void icon_kt_Click(object sender, EventArgs e)
        {

        }

        private void icon_kkt_Click(object sender, EventArgs e)
        {

        }

        private void icon_hc_Click(object sender, EventArgs e)
        {

        }

        private void icon_ccq_Click(object sender, EventArgs e)
        {
            label_tentieude.Text = "Quản Lý Chuyển Cơ Quan";
            navframe_content_managment.SelectedPage = page_ccq;
            nghiệpVụToolStripMenuItem1.Enabled = false;
            
        }

        private void icon_khac_Click(object sender, EventArgs e)
        {
            label_tentieude.Text = "Quản Lý Xử Lí Khác";
            navframe_content_managment.SelectedPage = page_xlk;
            nghiệpVụToolStripMenuItem1.Enabled = false;
            thêmToolStripMenuItem1.Enabled = false;
            sửaToolStripMenuItem1.Enabled = false;
            xóaToolStripMenuItem1.Enabled = false;
            thêmToolStripMenuItem.Enabled = false;
            sửaToolStripMenuItem.Enabled = false;
            xóaToolStripMenuItem.Enabled = false;
            gridControl_xlk.EmbeddedNavigator.Buttons.Remove.Enabled = false;
            gridControl_xlk.EmbeddedNavigator.Buttons.Append.Enabled = false;
        }

        private void icon_dangxuat_Click(object sender, EventArgs e)
        {

        }

      

        private void btn_nghiepvu_Click(object sender, EventArgs e)
        {

        }

        private void lưuToolStripMenuItem_Click(object sender, EventArgs e)
        {
           ColumnView view = gridcontrol_tinbao.FocusedView as ColumnView;
           view.CloseEditor();
           if (view.UpdateCurrentRow())
            {
             try
                    {
                        this.Validate();
                        this.tinBaoTableAdapter.Update(this.qltbDataSet21.TinBao);
                        xuLyKhacTableAdapter1.Update(qltbDataSet22.XuLyKhac);
                        MessageBox.Show("Lưu thành công");
                     }
              catch
                     {
                        MessageBox.Show("Lưu không thành công");
                     }
              }
        }

        private void gridView1_InitNewRow(object sender, InitNewRowEventArgs e)
        {
            //phai sort tang dan truoc khi lay du lieu
            // colSoTinBao.OptionsColumn.AllowEdit = true;

            this.qltbDataSet21.TinBao.DefaultView.Sort = "SoTinBao";
            var t = gridView1.GetRowCellValue(gridView1.GetRowHandle(gridView1.RowCount - 2), 
               colSoTinBao).ToString();
            string[] cautructinbao = t.Split('-');
            int nam = Convert.ToInt32(cautructinbao[1]);
            int sotb = Convert.ToInt32(cautructinbao[2]);
            if (nam == DateTime.Now.Year)
            {
                sotb++;
            }
            else
            {
                nam = DateTime.Now.Year;
                sotb = 1;
            }
            string tinbaomoi = "TB-" + nam+"-" + sotb;
          
            gridView1.SetRowCellValue(e.RowHandle, colSoTinBao, tinbaomoi);
            gridView1.SetRowCellValue(e.RowHandle, colTinhTrang, "Chưa xử lý");
            gridView1.SetRowCellValue(e.RowHandle, colNgayNhan, DateTime.Now);
        }

        private void thêmToolStripMenuItem_Click(object sender, EventArgs e)
        {
            gridView1.AddNewRow();
        }

        private void xóaToolStripMenuItem_Click(object sender, EventArgs e)
        {
            if (MessageBox.Show("Bạn có muốn xóa dòng này không ?", "Xác nhận xóa",
                    MessageBoxButtons.YesNoCancel, MessageBoxIcon.Question) == DialogResult.Yes)
            {
                string ketqua = gridView1.GetFocusedRowCellValue(colKetQua).ToString();
                if (ketqua != null)
                {
                   gridView3.FocusedRowHandle = gridView3.LocateByValue
                        (gridView3.Columns["SoQuyetDinh"].ToString(),ketqua);
                   gridView3.DeleteRow(gridView3.FocusedRowHandle);
                }
                gridView1.DeleteRow(gridView1.FocusedRowHandle);
            }
        }

        private void sửaToolStripMenuItem_Click(object sender, EventArgs e)
        {
            gridView1.ShowEditForm();
        }

        private void xuấtExcelToolStripMenuItem_Click(object sender, EventArgs e)
        {
            if (xuatExcelDialog.ShowDialog() == DialogResult.OK)
            {
                var compositeLink = new CompositeLinkBase();
                compositeLink.PrintingSystemBase = ps;

                var sheetTnBao = new PrintableComponentLinkBase();
                sheetTnBao.Component = gridcontrol_tinbao;
                var sheetXLK = new PrintableComponentLinkBase();
                sheetXLK.Component = gridControl_xlk;

                compositeLink.Links.Add(sheetTnBao);
                compositeLink.Links.Add(sheetXLK);

                var options = new XlsxExportOptions();
                options.ExportMode = XlsxExportMode.SingleFilePageByPage;

                compositeLink.CreatePageForEachLink();
                compositeLink.ExportToXlsx(xuatExcelDialog.FileName, options);


            }
        }

        private void xửLýKhácToolStripMenuItem_Click(object sender, EventArgs e)
        {

            string sotinbao = gridView1.GetFocusedRowCellValue(colSoTinBao).ToString();
            string soquyetdinh;

            xuLyKhacTableAdapter1.Update(qltbDataSet22.XuLyKhac);
            gridControl_xlk.RefreshDataSource();
            gridControl_xlk.Refresh();
            gridView3.RefreshData();

            if (qltbDataSet22.XuLyKhac.Rows.Count != 0)
            {
                //qltbDataSet22
                this.qltbDataSet22.XuLyKhac.DefaultView.Sort = "SoQuyetDinh";
                DataRow lastRow = qltbDataSet22.XuLyKhac.Rows[qltbDataSet22.XuLyKhac.Rows.Count - 1];
                soquyetdinh = lastRow["SoQuyetDinh"].ToString();
                string[] cautrucsqd = soquyetdinh.Split('-');
                int sqd = Convert.ToInt32(cautrucsqd[1]) + 1;
                soquyetdinh = cautrucsqd[0].ToString() + "-000" + sqd.ToString();
            }
            else {
                soquyetdinh="XLK-0001";
            }
            FormXuLiKhac formxulikhac = new FormXuLiKhac();
            formxulikhac.SoTinBao = sotinbao;
            formxulikhac.SoQuyetDinh = soquyetdinh;

            xuLyKhacTableAdapter1.Update(qltbDataSet22.XuLyKhac);
            qltbDataSet22.AcceptChanges();

            if (formxulikhac.ShowDialog() == DialogResult.OK)
            {
                gridView1.SetFocusedRowCellValue(colTinhTrang,"Đã Xử Lý");
                gridView1.SetFocusedRowCellValue(colKetQua, soquyetdinh);
                xuLyKhacTableAdapter1.Fill(qltbDataSet22.XuLyKhac);
                gridControl_xlk.RefreshDataSource();
                gridControl_xlk.Refresh();
                gridView3.RefreshData();
            }
            
        }

        private void chuyểnCơQuanToolStripMenuItem_Click(object sender, EventArgs e)
        {
            string sotinbao = gridView1.GetFocusedRowCellValue(colSoTinBao).ToString();
            string soquyetdinh;
            if (qltbDataSet21.ChuyenCoQuan.Rows.Count != 0)
            {
                this.qltbDataSet21.ChuyenCoQuan.DefaultView.Sort = "SoQuyetDinh";
                DataRow lastRow = qltbDataSet21.ChuyenCoQuan.Rows[qltbDataSet21.ChuyenCoQuan.Rows.Count - 1];
                soquyetdinh = lastRow["SoQuyetDinh"].ToString();
                string[] cautrucsqd = soquyetdinh.Split('-');
                int sqd = Convert.ToInt32(cautrucsqd[1]) + 1;
                soquyetdinh = cautrucsqd[0].ToString() + "-" + sqd.ToString();
            }
            else
            {
                soquyetdinh = "CCQ-0001";
            }
           //formchuyencoquan.SoTinBao = sotinbao;
           //formchuyencoquan.SoQuyetDinh = soquyetdinh;
          //formchuyencoquan.Show();
        }

        private void gridView1_RowClick(object sender, RowClickEventArgs e)
        {
            string t = gridView1.GetRowCellValue(e.RowHandle, colTinhTrang).ToString();
            if (t.CompareTo("Đã Xử Lý")==0)
            {
                nghiệpVụToolStripMenuItem1.Enabled = false;
            }
            else nghiệpVụToolStripMenuItem1.Enabled = true;
        }

        private void gridcontrol_tinbao_EmbeddedNavigator_ButtonClick(object sender, DevExpress.XtraEditors.NavigatorButtonClickEventArgs e)
        {
                        
            if (e.Button.ButtonType == NavigatorButtonType.Remove)
            {
                if (MessageBox.Show("Bạn có muốn xóa dòng này không ?", "Xác nhận xóa",
                    MessageBoxButtons.YesNoCancel, MessageBoxIcon.Question) == DialogResult.Yes)
                {
                    string ketqua = gridView1.GetFocusedRowCellValue(colKetQua).ToString();
                    if (ketqua != null)
                    {
                        gridView3.FocusedRowHandle = gridView3.LocateByValue
                             (gridView3.Columns["SoQuyetDinh"].ToString(), ketqua);
                        gridView3.DeleteRow(gridView3.FocusedRowHandle);
                    }
                    //co nen cap nhat lun xuong db hay ko
                 }
            }
        }

        void PrintingSystem_XlSheetCreated(object sender, XlSheetCreatedEventArgs e)
        {
            if (e.Index == 0)
                e.SheetName = "Tin Báo";
            else e.SheetName = "Xử Lý Khác";
        }

        void RefreshAll()
        {
            chuyenCoQuanTableAdapter1.Fill(qltbDataSet21.ChuyenCoQuan);
            xuLyKhacTableAdapter1.Fill(qltbDataSet22.XuLyKhac);
            this.tinBaoTableAdapter.Fill(this.qltbDataSet21.TinBao);

        }

        private void làmMớiToolStripMenuItem1_Click(object sender, EventArgs e)
        {
            RefreshAll();
        }
    }
}
