using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using ModernUIProject.Class;

namespace QuanLiTinBao
{
    public partial class panelMain : pnlSlider
    {
        //public event EventHandler MenuClosed;
        public panelMain(Form owner) : base(owner)
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
          
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
          
        }

        public void ShowMenu()
        {
            panel_menu.Visible = true;
            icon_managment.Visible = false;
        }

        public void CloseMenu()
        {
            panel_menu.Visible = false;
            icon_managment.Visible = true;
        }

        private void menu_tinbao_Click(object sender, EventArgs e)
        {
          
        }

        private void icon_trangchu_Click(object sender, EventArgs e)
        {

        }

        private void icon_tinbao_Click(object sender, EventArgs e)
        {

        }

        private void icon_kt_Click(object sender, EventArgs e)
        {

        }

        private void icon_kkt_Click(object sender, EventArgs e)
        {

        }

        private void icon_hc_Click(object sender, EventArgs e)
        {

        }

        private void icon_ccq_Click(object sender, EventArgs e)
        {

        }

        private void icon_khac_Click(object sender, EventArgs e)
        {

        }

        private void icon_dangxuat_Click(object sender, EventArgs e)
        {

        }
    }
}
